media/urls.py
from django.urls import path

from . import views

app_name = "media"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:user_id>', views.user_posts, name="user_posts"),
    path('profile/<int:user_id>', views.profile, name="user_profile"),
    path('profile/avatars/<int:user_id>', views.avatars, name="avatars")
]

posts/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sign_in/', include("sign_in.urls")),
    path('media/', include("media.urls")),
    path('api/', include("pub_posts.urls"))
]

sign_in/urls.py
from django.urls import path

from . import views

app_name = "sign_in"

urlpatterns = [
    path('', views.index, name = "index"),
    path('login', views.login_view, name="login"),
    path('sign_up', views.sign_up, name = "sign_up"),
    path('logout', views.logout_view, name="logout"),
    path('user', views.user, name="user")
]

sign_in/models.py
from django.db import models

# Create your models here.

sign_in/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from media.models import Profile

# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("sign_in:login"))
    return HttpResponseRedirect(reverse("sign_in:user"))

def login_view(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("sign_in:user"))
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("sign_in:user"))
        else:
            return render(request, "user/login.html", {
                "message": "Invalid credentials."
            })
    return render(request, "user/login.html")

def sign_up(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("sign_in:user"))
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            profile = Profile(user=user)
            profile.save()
            login(request, authenticate(request, username=request.POST["username"], password=request.POST["password1"]))
            return HttpResponseRedirect(reverse("sign_in:user"))
        return render(request, "user/sign_up.html", {
            'form': UserCreationForm().as_p(),
            'message': 'username or email already exists.'
        })
    return render(request, "user/sign_up.html", {
        'form': UserCreationForm().as_p()
    })

def logout_view(request):
    if request.user.is_authenticated:
        logout(request)
    return HttpResponseRedirect(reverse("sign_in:login"))

def user(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("sign_in:login"))
    return render(request, "user/user.html", {
        "username": request.user.username,
        "email": request.user.email,
        "user_id": request.user.id
    })

sign_in/templates/user/layout.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}

            {% endblock %}
        </title>
        
        <style>
            @keyframes bg-animation {
                0% {
                    background-position: 0% 50%;
                }

                50% {
                    background-position: 100% 50%;
                }

                100% {
                    background-position: 0% 50%;
                }
            }
            
            body {
                background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
                background-size: 400% 400%;
                background-position: left;
                animation: bg-animation 15s ease infinite;
                
            }

            .redirect-button {
                width: 30px;
                height: 10px;
                left: 10%;
                top: 50%;
                position: fixed;
            }

            .redirect-buttonposts {
                width: 30px;
                height: 10px;
                right: 10%;
                top: 50%;
                position: fixed;
            }

            .centered {
                width: max-content;
                height: max-content;
                background-color: regba(0, 0, 0, 0);
                position: fixed;
                top: 50%;
                left: 50%;
                padding: 20px;
                transform: translate(-50%, -50%);
                transition: 1s;
            }

            .centered:hover {
                transform: translate(-50%, -50%) scale(1.25);
            }

            .b {
                position: relative;
                left: 50%;
                transform: translate(-50%, 0%);
                text-align: center;
                border: 0;
                transition: 0.3s;
            }
            
            .b:hover {
                transform: translate(-50%, 0%) scale(1.5, 1.25);
            }
        </style>

        {%  block js_code  %}

        {%  endblock  %}
        
    </head>
    <body>
        {% block body %}

        {% endblock %}
    </body>
</html>

sign_in/templates/user/login.html
{% extends 'user/layout.html' %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="centered">
        <div>
            <form action="{% url 'sign_in:login' %}" method="POST">
                {% csrf_token %}
        
                <input type="text" placeholder="Username" name="username">
                <input type="password" placeholder="Password" name="password">
                <input type="submit" value="Login">
            </form>
            {% if message %}
                <h4>{{  message  }}</h4>
            {% endif %}
        </div>
        <div>
            <h3 style="display: inline-block">Not signed up yet? sign up here: </h3>
            <a href="{% url 'sign_in:sign_up' %}" style="display: inline-block"><h3>Sign Up</h3></a>
        </div>
    </div>
{% endblock %}

sign_in/templates/user/sign_up.html
{% extends 'user/layout.html' %}

{% block title %}
    Sign_up
{% endblock %}

{% block body %}
    <div class="centered">
        <form action="{% url 'sign_in:sign_up' %}" method="POST">
            {% csrf_token %}
    
            {{  form  }}
    
            <input type="submit" class="b" value="Sign up">
        </form>
        {%  if message  %}
            <h3>{{  message  }}</h3>
        {%  endif  %}
    </div>
{% endblock %}

sign_in/templates/user/user.html
{% extends 'user/layout.html' %}

{%  block title %}
    User
{% endblock %}

{%  block body %}
    <div class="centered">
        <div><h1>User</h1></div>
        <div>
            <div>
                <h3 style="display: inline-block">Username:</h3>
                <h4 style="display: inline-block">{{  username  }}</h4>
            </div>
            <div>
                <h3 style="display: inline-block">Email:</h3>
                <h4 style="display: inline-block">
                    {%  if email %}

                        {{  email  }}
                    
                    {% else %}

                        Unknown email.
                        
                    {%  endif  %}
                </h4>
            </div>
        </div>
        <div>
            <a href="{% url 'sign_in:logout' %}">
                <button class="b">
                    Logout
                </button>
            </a>
        </div>
    </div>
    <a href="{% url 'media:index'%}" class="redirect-button">
        <button>Posts</button>
    </a>
    <a href="{% url 'media:user_posts' user_id=user_id %}" class="redirect-buttonposts" style="right: 10%">
        <button>personal posts</button>
    </a>
{%  endblock %}